
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FilesAction;

	private global::Gtk.Action quitAction;

	private global::Gtk.VBox vbox3;

	private global::Gtk.MenuBar menubar2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label_file_path;

	private global::Gtk.Entry entry_file_path;

	private global::Gtk.Button button_view;

	private global::Gtk.Table table1;

	private global::Gtk.Entry entry_loaded_file_format;

	private global::Gtk.Entry entry_loaded_file_path;

	private global::Gtk.Label label_loaded_file_format;

	private global::Gtk.Label label_loaded_file_path;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button button_convert_to_wav;

	private global::Gtk.Button button_convert_to_bwav;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FilesAction = new global::Gtk.Action("FilesAction", global::Mono.Unix.Catalog.GetString("_Files"), null, null);
		this.FilesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Files");
		w1.Add(this.FilesAction, null);
		this.quitAction = new global::Gtk.Action("quitAction", global::Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Quit");
		w1.Add(this.quitAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-cdrom", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar2\'><menu name=\'FilesAction\' action=\'FilesAction\'><menui" +
				"tem name=\'quitAction\' action=\'quitAction\'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox3.Add(this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		this.hbox1.BorderWidth = ((uint)(6));
		// Container child hbox1.Gtk.Box+BoxChild
		this.label_file_path = new global::Gtk.Label();
		this.label_file_path.Name = "label_file_path";
		this.label_file_path.Xalign = 1F;
		this.label_file_path.LabelProp = global::Mono.Unix.Catalog.GetString("File path:");
		this.hbox1.Add(this.label_file_path);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label_file_path]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry_file_path = new global::Gtk.Entry();
		this.entry_file_path.CanFocus = true;
		this.entry_file_path.Name = "entry_file_path";
		this.entry_file_path.Text = global::Mono.Unix.Catalog.GetString("");
		this.entry_file_path.IsEditable = true;
		this.entry_file_path.InvisibleChar = '●';
		this.hbox1.Add(this.entry_file_path);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entry_file_path]));
		w4.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button_view = new global::Gtk.Button();
		this.button_view.CanFocus = true;
		this.button_view.Name = "button_view";
		this.button_view.Label = global::Mono.Unix.Catalog.GetString("View");
		global::Gtk.Image w5 = new global::Gtk.Image();
		w5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-jump-to", global::Gtk.IconSize.Menu);
		this.button_view.Image = w5;
		this.hbox1.Add(this.button_view);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button_view]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox3.Add(this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.entry_loaded_file_format = new global::Gtk.Entry();
		this.entry_loaded_file_format.CanFocus = true;
		this.entry_loaded_file_format.Name = "entry_loaded_file_format";
		this.entry_loaded_file_format.Text = global::Mono.Unix.Catalog.GetString("虚無");
		this.entry_loaded_file_format.IsEditable = false;
		this.entry_loaded_file_format.HasFrame = false;
		this.entry_loaded_file_format.InvisibleChar = '●';
		this.table1.Add(this.entry_loaded_file_format);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.entry_loaded_file_format]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entry_loaded_file_path = new global::Gtk.Entry();
		this.entry_loaded_file_path.CanFocus = true;
		this.entry_loaded_file_path.Name = "entry_loaded_file_path";
		this.entry_loaded_file_path.Text = global::Mono.Unix.Catalog.GetString("虚無");
		this.entry_loaded_file_path.IsEditable = false;
		this.entry_loaded_file_path.HasFrame = false;
		this.entry_loaded_file_path.InvisibleChar = '●';
		this.table1.Add(this.entry_loaded_file_path);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.entry_loaded_file_path]));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label_loaded_file_format = new global::Gtk.Label();
		this.label_loaded_file_format.Name = "label_loaded_file_format";
		this.label_loaded_file_format.Xalign = 1F;
		this.label_loaded_file_format.LabelProp = global::Mono.Unix.Catalog.GetString("Loaded file format:");
		this.table1.Add(this.label_loaded_file_format);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.label_loaded_file_format]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label_loaded_file_path = new global::Gtk.Label();
		this.label_loaded_file_path.Name = "label_loaded_file_path";
		this.label_loaded_file_path.Xalign = 1F;
		this.label_loaded_file_path.LabelProp = global::Mono.Unix.Catalog.GetString("Loaded file path:");
		this.table1.Add(this.label_loaded_file_path);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.label_loaded_file_path]));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox3.Add(this.table1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.table1]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button_convert_to_wav = new global::Gtk.Button();
		this.button_convert_to_wav.CanFocus = true;
		this.button_convert_to_wav.Name = "button_convert_to_wav";
		this.button_convert_to_wav.UseUnderline = true;
		this.button_convert_to_wav.Label = global::Mono.Unix.Catalog.GetString("Convert to WAV");
		global::Gtk.Image w13 = new global::Gtk.Image();
		w13.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
		this.button_convert_to_wav.Image = w13;
		this.hbox2.Add(this.button_convert_to_wav);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button_convert_to_wav]));
		w14.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button_convert_to_bwav = new global::Gtk.Button();
		this.button_convert_to_bwav.CanFocus = true;
		this.button_convert_to_bwav.Name = "button_convert_to_bwav";
		this.button_convert_to_bwav.UseUnderline = true;
		this.button_convert_to_bwav.Label = global::Mono.Unix.Catalog.GetString("Convert to BWAV");
		global::Gtk.Image w15 = new global::Gtk.Image();
		w15.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
		this.button_convert_to_bwav.Image = w15;
		this.hbox2.Add(this.button_convert_to_bwav);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button_convert_to_bwav]));
		w16.Position = 1;
		this.vbox3.Add(this.hbox2);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
		w17.Position = 3;
		w17.Expand = false;
		w17.Fill = false;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 652;
		this.DefaultHeight = 282;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.quitAction.Activated += new global::System.EventHandler(this.OnQuitActionActivated);
		this.button_view.Clicked += new global::System.EventHandler(this.OnButtonViewActivated);
	}
}
